FROM quay.io/prometheus/busybox:latest

ARG %TARGET_PROJECT%
ARG TARGETOS
ARG TARGETARCH

COPY /bin/%TARGET_PROJECT%-${TARGETOS}-${TARGETARCH} \
    /bin/%TARGET_PROJECT%
USER nobody
ENTRYPOINT ["/bin/%TARGET_PROJECT%"]